services:
  - type: web
    name: ctfd
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd_db
          property: connectionString
      - key: SECRET_KEY
        generate: true
    healthCheckPath: /health