services:
  - type: web
    name: ctfd
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /tmp/uploads
      cp -r ./uploads/* /tmp/uploads/
    startCommand: |
      gunicorn "CTFd:create_app()" --bind 0.0.0.0:10000 --worker-class gevent --workers 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
