services:
  - type: web
    name: ctfd-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "CTFd:create_app()" --bind 0.0.0.0:10000 --worker-class gevent --workers 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /var/uploads
    disk:
      name: ctfd-uploads
      mountPath: /var/uploads
      sizeGB: 1
    plan: free
    region: oregon
    autoDeploy: true

databases:
  - name: ctfd-db
    region: oregon
    plan: free
